app = "larvledger"
console_command = "php /var/www/html/artisan tinker"
primary_region = "ams"

[build]
dockerfile = "roadrunner.Dockerfile"

[env]
APP_ENV = "production"
APP_KEY = "base64:Zndza2ttMm9kbnNkcmlmeHlmYnlnb3RzOTJxMnBnNHY="
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
